services:
  api:
    build: ./api
    ports:
      - "8000:8000"
    volumes:
      - ./api:/app
      - pip-cache:/root/.cache/pip
    env_file:
      - ./api/.env
    depends_on:
      db:
        condition: service_healthy

  front:
    build: ./front
    ports:
      - "3000:3000"
    volumes:
      - ./front:/app
      - /app/node_modules
      - /app/.next
    env_file:
      - ./front/.env

  db:
    image: postgres:15
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
  # pgadmin4:
  #   image: dpage/pgadmin4
  #   env_file:
  #     - .env
  #   ports:
  #     - "8080:80"
  #   depends_on:
  #     - db
  # テスト用
  test:
    build: ./api
    command: ["pytest"]
    volumes:
      - ./api:/app
      - pip-cache:/root/.cache/pip
    env_file:
      - .env
    depends_on:
      - db
      - api

volumes:
  postgres-data:
  pip-cache:
